version: '2'

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: whattopick
      MYSQL_ROOT_PASSWORD: 123
  php:
    build:
        context: ./build
        dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www/whattopick
    entrypoint:
      - php-fpm
    links:
      - mysql
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes_from:
      - php
    volumes:
      - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    ports:
      - 8080:80